### ISSUE TITLE
Badges not appearing on main website

### ISSUE THREAD

**Issue by ShernanJ** [tejashah88/devpost-shields#1]
As shown below none of the badges are appearing on the site. Seeing as it was made 3 years ago, I guess time itself has broken this project, unfortunately :(

![image](https://user-images.githubusercontent.com/55066233/146102307-d99a9ada-f6af-43d5-9e61-80bbd1c5f87f.png)

**Comment by tejashah88** [comment]
@ShernanJ You need to enter the website of your project and click the "Search" button

**Comment by ShernanJ** [comment]
Should've read more first haha, thanks
